name: CI/CD

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker Insecure Registry
        run: |
          echo '{ "insecure-registries":["${{ secrets.NEXUS_REGISTRY }}"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker   

      - name: Login to Nexus Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_REGISTRY }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.NEXUS_REGISTRY }}/fastapi-realworld-example-app:latest
            ${{ secrets.NEXUS_REGISTRY }}/fastapi-realworld-example-app:${{ github.sha }}

      - name: Send Slack Notification on Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: "🚀 Uspešno izgrađena FastAPI aplikacija i poslata u Nexus!\nCommit: ${{ github.sha }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CICD_WEBHOOK_URL }}

      - name: Send Slack Notification on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: "❌ Došlo je do greške tokom CI/CD pipeline-a za FastAPI aplikaciju!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CICD_WEBHOOK_URL }}